config/routes.rb
Rails.application.routes.draw do

  get "posts/get_posts_tree" => 'posts#get_posts_tree', as: "get_posts_tree"
  get "posts/index_root" => 'posts#index_root', as: "index_root"
  get "posts/index_child" => 'posts#index_child', as: "index_child"
  get "posts/new/:id" => 'posts#new', as: "new_with_id"
  get "posts/get_ajax" => 'posts#get_ajax', as: "get_ajax"
  
  # get で posts/get_posts_tree にアクセスされたら、 postsコントローラーのget_posts_treeアクションを叩く。 asでget_posts_tree_pathの準備をしている？

  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  def set_post_id(id)
    @post_id = id
    self
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end
  
  def get_ajax
    @posts = Post.all
  end
  
  def post_id
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  # GET /posts/new/1 id1の投稿に対して返信
  def new
    @post = Post.new.set_post_id(params[:id] ? params[:id] : 0)
  end
  
  # GET /posts/1/edit
  def edit
  end
  
  def get_posts_tree
    @posts = Post.all
    respond_to do |format|
      format.js
      format.html
    end
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
#    @post.destroy
#    respond_to do |format|
#      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
#      format.json { head :no_content }
#    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:comment, :name, :post_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_show_posts.html.erb
<% if @posts.empty? %>
  <% %>
	<h3>投稿された記事はありません。</h3>
<% else %>
  <h3>投稿された記事</h3>
	<ul class="tree-menu">
		<li>Root<ul>
    <% @posts.each do |p| %>
      <li>
	    <%= p.id %>
		  <%= p.comment.truncate 20 %>
		  <%= p.name %>
		  <%= p.post_id %>
	    </li>
	  <% end %>
	</ul></li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trees</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :投稿内容 %>
    <%= f.text_area :comment %>
  </div>

  <div class="field">
    <%= f.label :投稿者名 %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :返信先（編集不可） %>
    <%= f.number_field :post_id%>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_toggle_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %>
    <%= f.text_area :comment %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <%= hidden_field_tag 'post_id', post.post_id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/get_ajax.js.erb
document.request_posts_with_ajax();

app/views/posts/get_posts_tree.js.erb
$('#result_div').html("<%= j(render 'layouts/show_posts') %>");

app/views/posts/index.html.erb
<script>
  $(document).ready(function() {
		$.ajax({
			url: "<%= get_posts_tree_path %>",
  		type: "GET",
			dataType: "script",
			success: function(data) {
			  $(".box").hide();
			},
		});
  	$('#section').change(function() {
  		$.ajax({
  			url: "<%= get_posts_tree_path %>",
				type: "GET",
				dataType: "script",
        success: function(data) {
					$(".box").hide();
					$("#post_new").hide();
				},
        error: function(data) {alert("エラーが発生しました。");}
  		});
  	});
		document.request_posts_with_ajax = function () {
			function post2html(post) {
				var sel0 = "#new";
				var sel1 = "#ul"+post.id;
				var sel2 = "ul"+post.id;
				
				var ret = '<li id="li'+post.id+'">#'+post.id+
				', 内容：'+post.comment.substring(0,20)+
				', 投稿者名：'+post.name+
				//', 返信：'+post.post_id+
				'<a href="javascript:$(\''+sel0+'\').prependTo(\''+sel1+'\');$(\'input#post_post_id\').val('+post.id+')">この投稿に返信する</a><ul id="'+sel2+'"></ul></li>'; 
				return ret;
			};
			$("#new").prependTo("#tree_menu")//一時的に逃がす
			$("#tree_here").html("情報を取得中です…");
			$.ajax({
				type: "GET", url: "posts.json", dataType: "json",
				success: function(data) {
					$("#tree_here").html("");
					for(var i in data) {
            var d = data[i];
            $(post2html(d)).appendTo("#li"+d.post_id+">ul");
				  }
					$(".box").hide();
					$("#new").prependTo("#tree_here")//ルートの位置に移動
				},
				error: function(data) {alert("失敗");}				
			});
	  	$("input#post_post_id").val(0).attr('readonly', true);
		};
		document.request_posts_with_ajax();


// 記事に返信するフォームを呼び出し
		document.request_new_post_with_ajax = function(post_id){
			$.ajax({
				type: "GET", url: "posts/edit/",
				dataType: "json",
				success: function(data) {
					$("#tree_here").html("");
					for(var i in data) {
            var d = data[i];
            $(post2html(d)).appendTo("#li"+d.post_id+">ul");
				  }
					$(".box").hide();
					$("#new").prependTo("#tree_here")//一時的に退避
				},
				error: function(data) {alert("失敗");}				
			});
		}
  });

</script>
<h2>Ajaxで①親投稿を取得して描画、②親投稿に取得した投稿を描画。</h2>
	<ul class="tree-menu">
		<li id="li0">#0 記事一覧<%= link_to '（ここをクリックすると最新情報を取得し表示を更新します）', get_ajax_path, remote: true, dataType: "script" %><ul id="tree_here">
	  </ul></li>
    <li id="new"><a href="javascript:$('#new_post').toggle();">新規投稿</a><%= render 'form', post: Post.new.set_post_id(0), remote: true %></li>
		
  </ul>

<hr/>

<h2>Ajaxで投稿一覧を取得できるようになった</h2>

<%= select_tag "section", options_for_select({" a. " => "a", " b. "=> "b"}, {id:"section"})%>

<div id="result_div">
	<h3>投稿一覧を取得中</h3>
</div>

<hr/>

<p id="notice"><%= notice %></p>

<h1>投稿一覧</h1>
<ul class="tree-menu">
  <li id="root">Root
		<ul>
			<li><a href="javascript:$('.box').toggle();">新規投稿（←クリックでフォーム開閉。）</a>
			<span class="box">
        <h2>New Post</h2>
        <%= render 'form', post: Post.new.set_post_id(0), remote: true %>
			</span>
			</li>

    <% @posts.reverse.each do |post| %>
        <li>＃<%= post.id %>
					：<%= post.comment.truncate 20 %>
					投稿者：<%= post.name %>
					親Id.<%= post.post_id %>
					操作：<%= link_to '返信', new_post_path %>|<%= link_to '見る', post %>|<%= link_to '編集', edit_post_path(post) %>|<%= link_to '削除', post, method: :delete, data: { confirm: 'Are you sure?' } %></li>
    <% end %>

    </ul>
  </li>
</ul>
<hr />
<h2>以下、Rails標準のindex表示</h2>
<table>
  <thead>
    <tr>
      <th>Id.</th>
      <th>Comment</th>
      <th>Name</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td></td>
        <td><%= link_to 'New Post', new_post_path %></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
    <% @posts.reverse.each do |post| %>
      <tr>
        <td><%= post.id %></td>
        <td><%= post.comment %></td>
        <td><%= post.name %></td>
        <td><%= post.post_id %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><% link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment:</strong>
  <%= @post.comment %>
</p>

<p>
  <strong>Name:</strong>
  <%= @post.name %>
</p>

<p>
  <strong>Post:</strong>
  <%= @post.post_id %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>